name: village_connect
description: "Village Connect â€“ Localized Social & Administrative Mobile Platform"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.8.1
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  image_picker: ^1.1.2
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
